Grocery <- c("QFC", "MARKETIME FOODS","PCC",
             "TRADER JOE'S","KEN'S MARKET",
             "SAFEWAY","THE FOOD CO-OP",
             "CVS","CENTRAL COOP",
             "WALGREENS",
             "FRED MEYER",
             "UWAJIMAYA",
             "99 RANCH", "METROPOLITAN MKT",
             "NEW SEASONS MAR", "NEW SEASONS MARKET",
             "H-MART US", "HMART",
             "CITY MARKET", "TOFU 101", "SEATTLE URBAN HONEY",
             "TARGET T", "BARTELL DRUG", "HAGGEN",
             "COSTCO WHSE")

Housing <- c("STATE FARM INSURANCEBLOOMINGTON",
             "OFFICE DEPOT", "EDMONDS HARDWARE & PEDMONDS",
             "DAISO",
             "Rent")

Entertainment <- c("MOSBY FARMS",
                   "THE PINE BOX", "ORCAS LANDING HOTEL",
                   "SEATTLE PARKS AND REC", "NORTHWEST OUTDOOR", "RACHELS GINGER BEER",
                   "STEAMGAMES.COM", "LAUGHING PLANET CAFE L", "MCDONALD'S",
                   "MEEKONG BAR", "ROCK BOX",
                   "THE TWO BELLS BAR",
                   "SIFF|SHALIMAR RESTAURANT",
                   "FORECASTERS PUBLIC HOUSE",
                   "SUMMIT PUBLIC HOUSE",
                   "STILL", "REDWOOD",
                   "FLYING CIRCUS", "SEATTLE BOULDERING", "REGAL THORNTON",
                   "Spotify",
                   "UW HUB GAMES AREA",
                   "GROUPON INC",
                   "HBO NOW",
                   "TM \\*TICKETMASTER",
                   "The Black Tux", "AMC ONLINE")

Restaurant <- c("RESTAURANT",
                "DAIRY QUEEN", "DIN TAI FUNG",
                "DOUGH ZONE DUMPLING", "CARL'S JR",
                "BLUE WATER TACO GRILL",
                "BLACKBIRD",
                "Dominos Pizza", "EINSTEIN BROS",
                "HOT CAKES MOLTEN CHOCOL",
                "IKINA SUSHI", "KONG TOFU HOUSE", "MACRINA",
                "RED ROBIN", "RAMEN MAN", "PORTAGE BAY CAFE",
                "PESTLE ROCK", "PASEO",
                "ORRAPIN THAI CUISINE",
                "NOREN SUSHI",
                "MOD PIZZA", "GOURMET NOODLE HOUSE",
                "STOP N SHOP",
                "BAR MELUSINE", "BOILING POINT", "CAFE FLORA",
                "CHANS PLACE", "TAMARI BAR", "FRANKS OYSTER HOUSE",
                "ISSIAN", "HONG KONG BISTRO", "JUNKICHI", "KAMONEGI",
                "KIN DEE", "KISAKU", "MANOLIN", "LOCKSPOT CAFE",
                "PATTY`S EGGNEST", "THAI CUISINE", "KANAME",
                "QIN XIAN", "SAM OH JUNG", "LOOKING FOR CHAI",
                "FREMONT BOWL", "SEN NOODLE BAR", "SEVEN STARS PEPPER",
                "PLENTY OF CLOUDS", "THAI WOODINVILLE", "THAI GINGER",
                "TENTENYU", "TENGU JAPANESE", "TAYLOR SHELLFISH OYSTER",
                "SWISH SWISH", "TUSCAN STONE PIZZA", "MAGNUSON CAFE",
                "ROCKET TACO", "TWO ELK VAIL", "UN BIEN", "SANTOUKA",
                "PHO BAC", "AYTTHAYA THAI", "RANCHO BRAVO TACOS",
                "MAIN STREET GRILL", "ANISE THAI CUISINE",
                "SAZERAC RESTAURANT", "GOLDEN SINGHA THAI", "ZEEKS PIZZA",
                "IL FORNAIO", "NIBBANA A THAI COOKERY", "RACONTEUR SEATTLE",
                "MANAO THAI", "MAMI TRAN",
                "WENDY'S", "POTBELLY", "BA BAR UNIVERSITY",
                "TST\\*CICCHETTI", "PATXIS - BALLARD",
                "PEASANT FOOD MANIFES",
                "BURGERVILLE CENTRALIA", "WATARU",
                "SKI HILL GRILL BRECKENRIDGE")

Bakery <- c("LE FOURNIL", "HAPPY LEMON",
            "LA PARISIENNE", "STARBUCKS",
            "CAFFE VITA COFFEE ROAS",
            "SEATTLE COFFEE WORKS",
            "KIKI BAKERY",
            "BAKERY CAFE",
            "BLACKBALL TAWAINESE", "BLACKBALL TAIWANESE",
            "BUTTERHORN BAKERY",
            "MIDORI BAKERY",
            "NANAS GREEN TEA",
            "REGENT CAKES AND BAKERY", "85C BAKERY CAFE",
            "SEA WOLF", "LA MARZOCCO CAFE", "FUJI BAKERY",
            "HIROKI", "ELM COFFEE ROASTERS", "DAMSEL & HOPPER",
            "YOUNG TEA",
            "ANCHORHEAD", "SHARETEA", "STUMPTOWN COFFEE",
            "STORYVILLE COFFEE",
            "FUEL COFFEE", "CAFE LADRO",
            "SALT & STRAW ICE", "PARFAIT ICE CREAM",
            "OLD SCHOOL FROZEN", "KURTWOOD FARMS",
            "LNH CAFE AND TEAHOUSSEATTLE")

Travel <- c("ALASKA AIRLINES",
            "AIRBNB")

Utilities <- c("SEATTLE CITY LIGHT",
               "COMCAST",
               "AT&T RECURR BILL",
               "AT&T MOBILE RECURRIN*")

Transportation <- c("BROWN BEAR", "CHEVRON",
                    "COSTCO GAS", "SHELL OIL",
                    "UNION 76",
                    "SEATTLE METER PARKING",
                    "SHELL Service", "ACE PARKING",
                    "STIA PUBLIC PARKING",
                    "COUNTERBALANCE BICYCSEATTLE",
                    "SEATTLE METER PARKINSEATTLE",
                    "WA VEHICLE LICENSINGOLYMPIA",
                    "ARROWS AUTOMOTIVE",
                    "DISCOUNT-TIRE-CO",
                    "BROWNBEAR CARWASH")

Donation <- c("FACEBK NetworkforGood",
              "SEATTLE HUMANE SOCIEBELLEVUE",
              "GG \\*RONALD MCDONALD",
              "SHMC/FOUNDATIONS")

Medical <- c("MED CTR")

categoryPatternsExample <- list(Grocery = Grocery,
                                Housing = Housing,
                                Entertainment = Entertainment,
                                Restaurant = c(Restaurant, Bakery),
                                Travel = Travel,
                                Utilities = Utilities,
                                Transportation = Transportation,
                                Donation = Donation,
                                Medical = Medical)

usethis::use_data(categoryPatternsExample)
