Grocery <- c("QFC", "MARKETIME FOODS","PCC",
             "TRADER JOE'S","KEN'S MARKET",
             "SAFEWAY","THE FOOD CO-OP",
             "CVS","CENTRAL COOP",
             "WALGREENS",
             "FRED MEYER",
             "UWAJIMAYA",
             "99 RANCH", "METROPOLITAN MKT",
             "NEW SEASONS MAR", "NEW SEASONS MARKET",
             "H-MART US", "HMART", "H MART SEATTLE",
             "CITY MARKET", "TOFU 101", "SEATTLE URBAN HONEY",
             "BARTELL DRUG", "HAGGEN",
             "COSTCO WHSE",
             "METROPOLITAN MARKET", "DAVIDSTEA",
             "(?=.*COUNTRY FARMS)(?=.*EDMONDS)",
             "RISING SUN FARMS",
             "(?=.*WHOLEFDS)(?=.*SEATTLE)",
             "Milstead and Company")

Housing <- c("STATE FARM INSURANCEBLOOMINGTON",
             "BEST BUY",
             "OFFICE DEPOT", "EDMONDS HARDWARE & PEDMONDS",
             "DAISO", "HOME GOODS * PORTLAND",
             "GOODWILL", 	"MERCER ISLAND THRIFTMERCER",
             "(?=.*TARGET)(?=.*PORTLAND)", "(?=.*TARGET)(?=.*NORTHGATE)",
             "(?=.*TARGET)(?=.*RENTON)", "(?=.*TARGET)(?=.*SEATTLE)",
             "(?=.*TARGET)(?=.*LYNNWOOD)", "(?=.*TARGET)(?=.*FACTORIA)",
             "(?=.*TARGET)(?=.*North Seattle)",
             "(?=.*TJ MAXX)(?=.* BELLEVUE)",
             "CRATE&BARREL", "CB2 SEATTLE", "SOHA LIVING",
             "PAPYRUS", "SKY GARDEN CENTER", "RAVENNA GARDENS",
             "(?=.*KITCHEN COLLECTION)(?=.*LINCOLN CITY OR)",
             "(?=.*MRS COOKS)(?=.*SEATTLE)",
             "Rent",
             "FEDEX",
             "USPS PO", "LOWE'S OF RAINIER",
             "MAPLE LEAF ACE", "SWANSONS NURSERY",
             "HOME DEPOT", "CORRYS FINE DRY",
             "MICHAELS STORES",
             "PHOTOSTAMPS EL SEGUNDO",
             "(?=.*REI SPRK)(?=.*SEATTLE)",
             "TURBOTAX",
             "KING CO RECORDERS")

Entertainment <- c("MOSBY FARMS",
                   "THE PINE BOX", "ORCAS LANDING HOTEL",
                   "SEATTLE PARKS AND REC", "NORTHWEST OUTDOOR",
                   "RACHELS GINGER BEER",
                   "LAUGHING PLANET CAFE L", "MCDONALD'S",
                   "(?=.*LE PANIER)(?=.*SEATTLE)",
                   "MEEKONG BAR", "LOWE'S OF RAINIERROCK BOX",
                   "THE TWO BELLS BAR",
                   "SIFF|SHALIMAR RESTAURANT",
                   "FORECASTERS PUBLIC HOUSE",
                   "SUMMIT PUBLIC HOUSE",
                   "STILL", "REDWOOD",
                   "FLYING CIRCUS", "SEATTLE BOULDERING",
                   "Spotify",
                   "UW HUB GAMES AREA",
                   "GROUPON INC",
                   "HBO NOW", "HBOMAX",
                   "TM \\*TICKETMASTER",
                   "VICTORIA S BRIDAL", "The Black Tux",
                   "AMC ONLINE",
                   "SEPHORA", "SPA NOIR INC", "AESOP.COM",
                   "ANTHROPOLOGIE", "CLUB MONACO", "ARITZIA U VILLAGE",
                   "LULULEMON", "ALLBIRDS * SEATTLE", "PAUL SMITH LLC",
                   "GREEN LAKE JEWELRY WORK", "FOLLAIN", "APOLLONAILSANDSPA.COSEATTLE",
                   "KIEHL'S * SEATTLE", "KIEHL'S ECOMM",
                   "JOE BAE SALON", "\\*THE MOTH 21", "GARY MANUEL AVEDA",
                   "GAP US", "GAP OUTLET", "OISELLE", "LOCCITANE", "KID S CLUB * SEATTLE",
                   "A EAGLE OUTFTR", "UNIQLO BELLEVUE",
                   "MANICA EP RELEAS", "PAYPAL \\*THE MOTH",
                   "BUFFALO EXCHANGE",
                   "SNOW.COM/VAIL RESORT", "EVOGEAR.COM", "EVO *- *SEATTLE",
                   "REG MERIDIAN", "REG *THORNTON", "REGAL THORNTON PLACE",
                   "BURKE-GILMAN BREWING", "SHS LILY AND PEARL",
                   "FIREWORKS-UNIVERSITYSEATTLE", "PARTY @ DISPLAY & COSTU",
                   "SEES CANDIES", "(?=.*PAPRYUS)(?=.*SEATTLE)",
                   "(?=.*FLATSTICK PUB)(?=.*Seattle)",
                   "(?=.*FLATSTICK PUB)(?=.*SEATTLE)",
                   "ROBOT VS SLOTH",
                   "STEAM GAMES WA", "ETSY.COM",
                   "MOON VALLEY ORGADEMING",
                   "MUD BAY")

Restaurant <- c("RESTAURANT",
                "DAIRY QUEEN", "DIN TAI FUNG",
                "DOUGH ZONE DUMPLING", "CARL'S JR",
                "BLUE WATER TACO GRILL",
                "BLACKBIRD",
                "Dominos Pizza", "EINSTEIN BROS",
                "HOT CAKES MOLTEN CHOCOL",
                "IKINA SUSHI", "KONG TOFU HOUSE", "MACRINA",
                "RED ROBIN", "RAMEN MAN", "PORTAGE BAY CAFE",
                "PESTLE ROCK", "PASEO",
                "ORRAPIN THAI CUISINE",
                "NOREN SUSHI",
                "MOD PIZZA", "GOURMET NOODLE HOUSE",
                "STOP N SHOP",
                "BAR MELUSINE", "BOILING POINT", "CAFE FLORA",
                "CHANS PLACE", "TAMARI BAR", "FRANKS OYSTER HOUSE",
                "ISSIAN", "HONG KONG BISTRO", "JUNKICHI", "KAMONEGI",
                "KIN DEE", "KISAKU", "MANOLIN", "LOCKSPOT CAFE",
                "PATTY`S EGGNEST", "THAI CUISINE", "KANAME",
                "QIN XIAN", "SAM OH JUNG", "LOOKING FOR CHAI",
                "FREMONT BOWL", "SEN NOODLE BAR", "SEVEN STARS PEPPER",
                "PLENTY OF CLOUDS", "THAI WOODINVILLE", "THAI GINGER",
                "TENTENYU", "TENGU JAPANESE", "TAYLOR SHELLFISH OYSTER",
                "SWISH SWISH", "TUSCAN STONE PIZZA", "MAGNUSON CAFE",
                "ROCKET TACO", "TWO ELK VAIL", "UN BIEN", "SANTOUKA",
                "PHO BAC", "AYTTHAYA THAI", "RANCHO BRAVO TACOS",
                "MAIN STREET GRILL", "ANISE THAI CUISINE",
                "SAZERAC RESTAURANT", "GOLDEN SINGHA THAI", "ZEEKS PIZZA",
                "IL FORNAIO", "NIBBANA A THAI COOKERY", "RACONTEUR SEATTLE",
                "MANAO THAI", "MAMI TRAN",
                "WENDY'S", "POTBELLY", "BA BAR UNIVERSITY",
                "TST\\*CICCHETTI", "PATXIS - BALLARD",
                "PEASANT FOOD MANIFES",
                "BURGERVILLE * CENTRALIA", "WATARU",
                "BAMBOO SUSHI", "THE WALRUS AND SEATTLE",
                "AFURI", "SUIKA SEATTLE", "MATSU * SEATTLE",
                "MAMA MELINA", "MYUNG DONG TOFU", "FRAN'S CHOCOLATES",
                "STATESIDE * SEATTLE", "CHERYL'S ON 12TH * PORTLAND",
                "MR. WEST CAFE BAR", "DELFINOS CHICAGO STY",
                "VALHALLA SANDWICHES", "STRETCH THE NOODLE",
                "RAVENNA BREWING", "TAMALE BOY RUSSELL",
                "SONIC DRIVE IN", "POKEWORKS", "MEXICO CANTINA .*[SEATTLE]",
                "BLUEACRE SEAFOOD", "EIGHT ROW", "FRELARD PIZZA",
                "TASTE OF XIAN", "SIZZLING POT KING", "KRUA THAI FAMILY KITCHE",
                "YIFANG TAIWANESE", "JAPONESSA SEATTLE", "JACK'S FISH SPOT",
                "HUI LAU SHAN", " GREAT STATE BUR",
                "SHAKE SHACK", "(?=.*SOUTHPAW)(?=.*SEATTLE)",
                "PAGLIACCI", "YALLA SEATTLE",
                "MILK DRUNK", "SHUGS, LLC SEATTLE",
                "UNIVERSITY KIDD")

Bakery <- c("LE FOURNIL", "HAPPY LEMON",
            "LA PARISIENNE",
            "STAHARDWICKS AND SONSRBUCKS", "HARDWICKS AND SONS",
            "CAFFE VITA COFFEE ROAS",
            "SEATTLE COFFEE WORKS",
            "KIKI BAKERY",
            "BAKERY CAFE",
            "BLACKBALL TAWAINESE", "BLACKBALL TAIWANESE",
            "BUTTERHORN BAKERY",
            "MIDORI BAKERY",
            "NANAS GREEN TEA",
            "REGENT CAKES AND BAKERY", "85C BAKERY CAFE",
            "SEA WOLF", "LA MARZOCCO CAFE", "FUJI BAKERY",
            "HIROKI", "ELM COFFEE ROASTERS", "DAMSEL & HOPPER",
            "YOUNG TEA",
            "ANCHORHEAD", "SHARETEA", "STUMPTOWN COFFEE",
            "STORYVILLE COFFEE",
            "FUEL COFFEE", "CAFE LADRO",
            "SALT & STRAW ICE", "PARFAIT ICE CREAM",
            "NUTTY SQUIRREL",
            "OLD SCHOOL FROZEN", "KURTWOOD FARMS",
            "LNH CAFE AND TEAHOUSSEATTLE", "BAKERY NOUVEAU",
            "MATCHA CAFE MAIKO", "BLUE STAR DONUT", "ZOKA COFFEE",
            "HEART COFFEE", "THE FRENCH BAKEKIRKLAND",
            "(?=.*UPTOWN ESPRESSO)(?=.*Seattle)", "KITANDA ESPRESSO AND",
            "(?=.*RAISED DOUGHNUTS)(?=.*Seattle)", "LE BON BAKERY",
            "(?=.*LE REVE)(?=.*SEATTLE)", "GENERAL PORPOISSEATTLE",
            "TAPIOCA EXPRESS", "BELLE EPICUREANSEATTLE",
            "CRUMBLE & FLAKE", "LE PANIER SEATTLE",
            "STARBUCKS STORE", "SWEDISH FH STARBUCKS")

Travel <- c("ALASKA AIRLINES",
            "AIRBNB",
            "HAWAIIAN AIRLINES",
            "EVA AIRWAYS", "EVA AIR SEA TICKET",
            "EVOLVE VACATION RENTDENVER",
            "SPIRIT AIRLINES",
            "PARK N JET", "BEECHER .*[SEATASETAC]",
            "SKI HILL GRILL *BRECKENRIDGE",
            "PAPA HAYDN W JO BAR PORTLAND",
            "(?=.*7-11)(?=.*HALEIWA)", "(?=.*TED'S BAKERY)(?=.*HALEIWA)",
            "ALICIAS MARKET *HONOLULU", "HELE KING & COOKE *HIHONOLULU",
            "(?=.*SOBA-YA)(?=.*HONOLULU)", "AHI & VEGETABLE 6500HONOLULU",
            "NIO SNOW ICE AND TEAHONOLULU", "(?=.*STORE #6 GATE 29)(?=.*HONOLULU)",
            "(?=.*/*WOW WOW)(?=.*HAWAIIAN)", "7-11 HALEIWA",
            "(?=.*/*MALAMA MARKET KBC)(?=.*HALEIWA)",
            "(?=.*TED'S BAKERY)(?=.*HALEIWA)",
            "(?=.*FLORET)(?=.*SEATAC)",
            "FOODLAND PUPUKEA", "DOLE PLANTATION", "WALL MART SUPER CENTHONOLULU",
            "HARRAH'S HOTEL", "HOMEAWAY", "(?=.*BELLAGIO)(?=.*CAFE.)",
            "HONOLULU COOKIE", "(?=.*KAHUKU FARMS)(?=.*Kahuku)",
            "BRUG BAKERY ALA MOANHONOLULU",
            "(?=.*SWEET BOBA)(?=.*LAS VEGAS)",
            "Caadxi Oaxaca * Snoqualmie", "(?=.*HERFYS BURGER)(?=.*SNOQUALMIE)",
            "COSMO DISTRICT DONUTLAS VEGAS", "LOBSTER ME",
            "(?=.*COSMO WICKED SPOON)(?=.*LAS VEGAS)",
            "WSFERRIES",
            "SALTY GIRLS SEQUIM", "MUKILTEO COFFEE",
            "(?=.*OYSTERCATCHER)(?=.*COUPEVILLE)",
            "DOC S MARINA GRBAINBRIDGE",
            "(?=.*MORA ICED CREAMERY)(?=.*BAINBRIDGE)",
            "SALT HOUSE MERCANTILBainbridge",
            "HITCHCOCK DELICBAINBRIDGE",
            "(?=.*DUFRY ST)(?=.*SEATAC)",
            "CITY OF PORTLAND DEPPORTLAND", "SMART PARK 10TH & YAPORTLAND",
            "WASHINGTON PARK PARKPORTLAND",
            "(?=.*WAL-MART)(?=.*WARRENTON)")

Utilities <- c("SEATTLE CITY LIGHT",
               "PUGET SOUND ENERGY",
               "COMCAST",
               "AT&T RECURR BILL",
               "AT&T MOBILE RECURRIN*")

Transportation <- c("BROWN BEAR", "CHEVRON",
                    "COSTCO GAS", "SHELL OIL",
                    "UNION 76",
                    "SEATTLE METER PARKING",
                    "SHELL Service", "ACE PARKING",
                    "STIA PUBLIC PARKING",
                    "WSCC ONLINE PARKING SEATTLE",
                    "COUNTERBALANCE BICYCSEATTLE",
                    "SEATTLE METER PARKINSEATTLE",
                    "WA VEHICLE LICENSINGOLYMPIA",
                    "ARROWS AUTOMOTIVE",
                    "DISCOUNT-TIRE-CO",
                    "BROWNBEAR CARWASH")

Donation <- c("FACEBK NetworkforGood",
              "SEATTLE HUMANE SOCIEBELLEVUE",
              "GG \\*RONALD MCDONALD",
              "SHMC/FOUNDATIONS", "SEATTLE HUMANE",
              "WORLD WIDE FUND FOR ULTIMO",
              "ACTBLUE",
              "WENATCHEEHUMANE")

Medical <- c("MED CTR", "ULTRA CHIROPRACTIC", "ACTION SPORTS MASSAG",
             "GREEN LAKE ORAL")

categoryPatternsExample <- list(Grocery = Grocery,
                                Housing = Housing,
                                Entertainment = Entertainment,
                                Restaurant = c(Restaurant, Bakery),
                                Travel = Travel,
                                Utilities = Utilities,
                                Transportation = Transportation,
                                Donation = Donation,
                                Medical = Medical)

usethis::use_data(categoryPatternsExample)
